spring:
  application:
    security:
      config:
        jwt:
          secret: "dio123"
          prefix: "Bearer"
          key: "SECRET_KEY"
          expiration: 3600000
  datasource:
    url: jdbc:h2:mem:ifood_db
    username: dio
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  springdoc:
    api:
      docs:
        path: /v3/api-docs
    swagger:
      ui:
        path: /swagger-ui.html
    packages-to-scan: me.dio.innovation.one